### ISSUE TITLE
Step 4-projects instructions give only the total number of changes to be expected

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-example-foundation-app#43]
## Expected Behavior

User should be informed of which and how many resources will be created so that they can validate their terraform plan.

## Actual Behavior

In 4-projects step 8, only the total number of changes is provided: **63**

```
8. Run terraform plan, this should report 63 changes to be added if using the default config.
```

If the number does not match we don't know how to find out which one is missing or is in excess.

In a deploy the total number was actually **64** changes.

## Steps to Reproduce the Problem

1. Follow the steps up to https://github.com/rutalreja-deloitte/terraform-example-foundation-app/tree/doc/trouble/foundation-extension/4-projects
1.
1.

## Specifications

- Version: 6645d8112fec6595d74a2c49348503f89066aa59
- Platform: linux

**Comment by bharathkkb** [comment]
@daniel-cit do we have this sort of verbiage in any of example-foundation? I propose we remove this as the modules can change from underneath (say we add something in project factory in minor release) and this deployment could be unaffected but give users the false impression that it did not work. It also increases maintenance since we will need to track these and lint will not warn us.

We should just use integration test (tracking https://github.com/GoogleCloudPlatform/terraform-example-foundation-app/issues/21) to validate success.

**Comment by daniel-cit** [comment]
@bharathkkb we don't have this kind of recommendation to count the resources in the foundation
I agree with letting the integration tests to validate the success of the code.
